eval_metrics
sign-language-processing/transcription pull request #13
Opened 2023-04-25 16:46 UTC by J22Melody

feat(pose_to_segments): add evaluation metrics and ensure data correctness

2023-04-25 16:47 UTC, J22Melody commented on pose_to_segments/src/data.py
> +        while timestamp_i < (len(timestamps) - 1) and timestamps[timestamp_i] < segment["end_time"]:
@AmitMY this should fix a index bug

2023-04-25 21:16 UTC, AmitMY requested changes

2023-04-25 21:16 UTC, AmitMY commented on pose_to_segments/src/utils/metrics.py
> +def frame_accuracy(probs, gold):
can you please:
1. in a comment, add the expected shape of `probs` and `gold`?
2. add python typing (`frame_accuracy(probs: torch.Tensor....`)

2023-04-25 21:16 UTC, AmitMY commented on pose_to_segments/src/train.py
> +            train_loader = DataLoader(train_dataset, batch_size=args.batch_size, shuffle=False, collate_fn=zero_pad_collator)
indentation looks wrong

2023-04-25 21:16 UTC, AmitMY commented on pose_to_segments/src/model.py
> +            fps = 25
`fps` is actually a parameter in the data. looking at `batch["pose"]["obj"].body.fps` should give you the number as well

2023-04-26 12:01 UTC, AmitMY approved these changes

2023-04-26 12:01 UTC, merged